# src/qoder/config/defaults.py

DEFAULT_CONFIG = {
    "project": {
        "name": "Untitled",
    },
    "llm": {
        "provider": "openai",
        "model": "gpt-4",
        "temperature": 0.2,
        "max_tokens": 4096,
    },
    "test": {
        "case_dir": "tests/cases",
        "script_dir": "tests/scripts",
        "plan_dir": "tests/plans",
        "default_framework": "playwright",
    },
    "ui": {
        "base_url": "http://localhost:3000",
        "default_browser": "chromium",
    },
    "api": {
        "base_url": "http://localhost:8000",
        "timeout": 30,
    },
    "knowledge": {
        "enabled": True,
        "source_dirs": ["requirements", "docs", "tests/cases"],
    },
    "script_generator": {
        "name": "script_generator",
        "version": "1.0.0",
        "type": "test_generation",
    },
}

# conftest.py 模板(简化版,完整版见技能规范 §10)
UI_CONTEST_TEMPLATE = '''"""conftest.py - Generated by qoder test script"""
import os
import pytest
from playwright.sync_api import sync_playwright

def pytest_addoption(parser):
    parser.addoption("--base-url", default="http://localhost:3000")
    parser.addoption("--browser-name", default="chromium",
                     choices=["chromium", "firefox", "webkit"])

@pytest.fixture(scope="session")
def base_url(pytestconfig):
    return pytestconfig.getoption("--base-url")

@pytest.fixture
def page(base_url):
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()
        yield page
        context.close()
        browser.close()
'''

API_CONTEST_TEMPLATE = '''"""conftest.py - Generated by qoder test script"""
import os
import pytest
import httpx

def pytest_addoption(parser):
    parser.addoption("--api-base-url", default="http://localhost:8000")

@pytest.fixture(scope="session")
def api_base_url(pytestconfig):
    return pytestconfig.getoption("--api-base-url")

@pytest.fixture(scope="session")
def api_client(api_base_url):
    with httpx.Client(base_url=api_base_url, timeout=30.0) as client:
        yield client
'''


def get_conftest_template(framework: str) -> str:
    """获取 conftest.py 模板"""
    if framework == "playwright":
        return UI_CONTEST_TEMPLATE
    return API_CONTEST_TEMPLATE
